# Generated by Django 5.2.15 on 2026-07-05 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_donor_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='source_hospital',
            field=models.ForeignKey(blank=True, help_text='Hospital the blood is collected from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_dispatches', to='core.hospital'),
        ),
    ]
